### ISSUE TITLE
[V1][BUG] Small bugs and inconsistencies need to be fixed

### ISSUE THREAD

**Issue by adar2378** [djangoflow/flutter-odoo-timesheets#36]
- [x] Task or project not found error when uploading a local task after logging in

- [x] Sync with odoo button shows wrongly when submitting a task to odoo

- [x] Timer not started shows wrongly sometimes in the Task details page and throws error while stopping timer saying "timer was not started yet"

- [x] Need to show syncing status when the data is being synced with odoo

- [ ] Need to show current task types (odoo, or local in tasks page)

- [ ] Update icons following the design

**Comment by ivan1px** [comment]
- [ ] Closing and re-openening the app with running timer causies to diplsy stop button for a second 
- [ ] Local -> odoo task descrption field must be mandatory 
- [ ] Display proper error when trying to sync task without the internet

**Comment by adar2378** [comment]
@ivan1px excellent, I totally forgot about internet connection related error handling specially

**Comment by ivan1px** [comment]
Will track using #47
