### ISSUE TITLE
[FE] Remaining features

### ISSUE THREAD

**Issue by adar2378** [djangoflow/flutter-odoo-timesheets#45]
- [ ] Sorting timesheets most recenty, oldest etc
- [ ] Favorite project interaction, currently it is read only
- [ ] Editing/delete local task, project, timesheet interaction
- [ ] Github login and UX for github related syncing etc
- [ ] Update package name to com.apexive.timesheet
- [x] https://github.com/djangoflow/flutter-odoo-timesheets/issues/38

cc @ivan1px

**Comment by ivan1px** [comment]
Duplicate of #47
