### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by sofiapex** [djangoflow/flutter-odoo-timesheets#46]
- [ ] loading logo is strange. Remove square background
- [ ] Make the loading screen a bit longer - now it looks like a bug
- [ ] remove background ![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/75428552/e4e76ed6-e58d-49d9-8b62-a03ab180d7f7)
- [ ] new created task, timer started, cannot stop ![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/75428552/71937975-b9ae-4afc-a27b-fd97b749a118)
- [ ] Cannot sync after timer stop   ![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/75428552/06df0f98-91d0-4b16-94ec-57e9918b1518)
- [ ] timesheets should be sorted - the latest on the top
- [ ] add interaction on scroll same as in turnaround app see here https://uploads-ssl.webflow.com/609ccf5d994ce7740cc92684/62f22d31562f475fc563f332_Copy%20of%20Fun%20Hand-drawing%20Steps%20Infographic%20Instagram%20Post.gif
- [ ] https://github.com/djangoflow/flutter-odoo-timesheets/assets/75428552/02f6c47d-546e-45f2-aef7-24a1f769e79e

**Comment by ivan1px** [comment]
@adar2378 Not able to test properly, keep gettings this errors

Version 1.0.0(8)
Android 
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/1050d12d-d653-4218-8214-6c9998523404)
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/7177bbf0-c424-4a4b-be09-938b57ffdd00)
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/8078fb9d-0020-47c4-b260-79e6fb5810df)
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/40c6e3c4-2b58-488b-8f43-6ce4ce5862d4)

**Comment by adar2378** [comment]
@ivan1px please try to uninstall and install again
