### ISSUE TITLE
Timesheets Design Update

### ISSUE THREAD

**Issue by ivan1px** [djangoflow/flutter-odoo-timesheets#47]
### Logo 

- [x] Update the logo based on the design:
[Apple](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=38%3A8702&mode=design&t=ud3AlOqjRjXDY1tz-1)
[Android](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=38%3A8702&mode=design&t=ud3AlOqjRjXDY1tz-1)
- [x] Update the splash screen
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/47354e56-56c9-4d32-a80b-be14132291f4)

### Look/Feel

- [x] Update design based on the [Figma file ](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=0%3A1&mode=design&t=3kPeLpq2NQFSW0HL-1)
- [x] Drop-up menus should have glass effect
- [x] After drop-up menu is displayed the rest of the screen should be a bit more dark

### Interactions

- [x] add interaction on scroll same as in turnaround app [see here ](https://uploads-ssl.webflow.com/609ccf5d994ce7740cc92684/62f22d31562f475fc563f332_Copy%20of%20Fun%20Hand-drawing%20Steps%20Infographic%20Instagram%20Post.gif)

Ideas of what can be added if not too complicated:
- Card Flip for Details: When a user taps on a timer card to see more details, the card could flip over in a 3D animation to reveal additional information.
- Drag-and-Drop Sorting: Allow users to sort timers by dragging and dropping them, with the other cards making way in a fluid, animated manner. (Then we will need to add a "default" option for sorting)
- Project Expansion: When a user taps on a project, it could expand in a fluid animation to reveal the tasks within, perhaps even with a spring or bounce effect at the end.
- Color Transition: When switching between projects, the background color could smoothly transition to match the color theme of the selected project.
- Theme Transition: When switching between light and dark modes, instead of an instant change, have a gradual transition where each UI element changes theme in a staggered manner.
- Feel free to propouse something new

## Login
[Design](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1391%3A3568&mode=design&t=3kPeLpq2NQFSW0HL-1)

- [x] add an icon to display/hide password

## Timesheets
[Design screens](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1354%3A2220&mode=design&t=3kPeLpq2NQFSW0HL-1)
- [x] When the tab is not empty screen display Sorting button
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/a0f3db3b-9c25-439c-9ae1-4de568b837af)

- [x] Clicking on the Sorting button should open the drop down with two options: Recent/Oldest
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/4085c8e8-9d75-408e-9549-e35e8e06bbf2)

- [x] Recent should be selected by default
- [x] Selecting on of this options should sort the timers by their last time of execution

- [x] #55
- [x] Clicking on Plus button should open the Create timer screen
- [x] Star icon indicates if the task if favorited, you can click on it in order to favorite
- [x] Favorite logic should be applied to the timesheet, noty the task (it will make all timesheets inside favorite as well)
- [x] Do not display the deadline in case it's not set

### Timer creation

- [x] Clicking on the plus button should navigate to the [Timer creation](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1377%3A1383&mode=design&t=3kPeLpq2NQFSW0HL-1)
- [x] User should be able to click on the Project field and start typing, dropdown list should be filtered based on the input
- [x] If there is no match or this is the first project user should see "Create this Project" button
- [x] Project title field should act as a search field (e.g. like we had with tags in the AH) we should not have two different fields as we had in the previous version
- [x] User should be able to click on the Task field and start typing, dropdown list should be filtered based on the input
- [x] If there is no match or this is the first task user should see "Create this Task" button
- [x] Task title field should act as a search field (e.g. like we had with tags in the AH) we should not have two different fields as we had in the previous version
- [x] Display Description field
- [x] Display "Make Favorite" check box
- [x] Information if timer is Favorited stored localy 
- [x] When selecting a project we need to display in the list if it local or odoo via icon

### Opened the Timer
[Design link](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1442%3A2116&mode=design&t=3kPeLpq2NQFSW0HL-1)

- [x] There are should be two tabs: Timesheets and Details
- [x] On the Timesheets display Current running/last timer information (day of the week, date, Start time, Time, description)
- [ ] User should be able to click on the pencil button to edit the description
- [x] Below there will be a list of completed records, by default they are collapsed and displaying like this:
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/e4b222f3-b898-480a-8101-80c88414ed73)

- [x] Clicling on the record will expand it and display Description with edit button
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/01b0c698-0326-441d-8676-7e0d2ee780b7)

- [x] In case there is more than 2 lines of text we need to cut it with "Read more" and ... after the last symbol 
- [x] Clicking Read more should display all text
- [x] On the Details tab display task details (Project, Deadline (if exist), Assigned to, Task descruption)
- [x] Clicking on the three dots button should display a drop-up menu with two options for local task: delete/favorite and one option for synced task: favorite

### Favorites

- [x] Add a new tab "Favorites"
- [x] [Empty screen](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1354%3A2135&mode=design&t=3kPeLpq2NQFSW0HL-1)
- [x] Cliclicking on the Get started should open Create timer screen with "Make favorite" checkbox on

### Odoo

- [x] Rename Synced to Odoo
- [x] [Empty screen ](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1375%3A994&mode=design&t=3kPeLpq2NQFSW0HL-1)
- [x] Clicking Get started should open Odoo log-in screen

### Local

- [x] [Empty screen](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1354%3A2043&mode=design&t=3kPeLpq2NQFSW0HL-1)
- [x] Clicking Get started should open Create timer screen

## Projects

- [x] Clicking on the "Get started" on [Empty odoo projects screen](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1375%3A1076&mode=design&t=al1mevCATrT5UMqU-1) will open odoo log-in screen

- [x] Clicking on the "Get started" on [Empty local projects screen](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1372%3A1400&mode=design&t=al1mevCATrT5UMqU-1) will open create project screen

- [x] Clicking on the "Get started" on [Empty fav projects screen](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1364%3A907&mode=design&t=al1mevCATrT5UMqU-1) will open create project screen with favorited checkbox on

- [x] User should be able to click on the plus button to create a new project

### Create project

- [x] User should input name/color (the same as we have in odoo)
- [x] If it favorite 

### Inside the project
- [x] User should be able to click on the three donts inside the project and see a drop-up menu with two options for local task: delete/favorite and one option for synced task: favorite
- [ ] Display timer near the task inside the project
- [x] In case there is no tasks in local project display an [empty screen](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1417%3A2188&mode=design&t=al1mevCATrT5UMqU-1), clicking on get started should opne the timer creation page
- [x] In case there is no tasks in odoo project display an [empty screen](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1394%3A1102&mode=design&t=al1mevCATrT5UMqU-1), clicking on button should re-sync the tasks data

## Settings
[Design screens](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1112%3A1684&mode=design&t=al1mevCATrT5UMqU-1)

- [x] By default there is should be a light theme on
- [x] User can switch to the[ dark theme ](https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?type=design&node-id=1394%3A2041&mode=design&t=al1mevCATrT5UMqU-1)
- [x] Under the Synchronizations  display only odoo
- [x] Clicking on the account should display the drop-up with two options: unlink the account and Re-sync
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/d05d6a52-40f7-40f0-bff8-9d3ae8584356)

## Edge cases and other

- [ ] When syncing with odoo https://  should not be editable as without it the url will be incorrect
- [x] Improve dropdown visuals, it should not display so much empty space
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/2afe753d-33ce-47dd-b3a2-2953b02daddc)

- [x] I belive that Timer should start if you click on the area with time on the card, not only start/pause 
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/556db928-570c-4216-8654-57e6c7b56ea5)
- [x] Update package name to com.apexive.timesheet
- [x] When syncing an already sycned **timesheet** from odoo, the odoo task can be deleted, in this case we need to show user a pop up to choose if they want to delete the local timesheet entry as well, or want to keep it

- [x] If an online Task or Project was deleted then the user will need to sync Task from odoo to select a Odoo project and Odoo Task. This will also update the onlineIds for local Task and Project

- [ ] If a timesheets online project id and task id was change from odoo then we will need to create a new Task or Project or both on local db and update the onlineIds there and update the local timesheet to refer to the new projectId and TaskId. Basically transfer the timesheet to the new Task.
- [ ] when user logs out then then local db should be saved, after he log-in back it should sync with online db and not create duplicates
- [x] If task is deleted in the odoo we need to display a question oppon the sync if we should delete it as well or keep locally
- [ ] If there is a issue with task id we need to display a question what we need to do with it (merge, create new, ignore) 

## Bugs fixes 

- [ ] Inside the task I can see list of around 20 timers (not timesheets)
![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/116165418/4bbcee37-0340-48c7-af78-40c72519e2e2)

- [ ] new created task, timer started, cannot stop ![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/75428552/71937975-b9ae-4afc-a27b-fd97b749a118)
- [ ] Cannot sync after timer stop   ![image](https://github.com/djangoflow/flutter-odoo-timesheets/assets/75428552/06df0f98-91d0-4b16-94ec-57e9918b1518)

**Comment by ivan1px** [comment]
@turabiapex

**Comment by ajil-apx** [comment]
**Display timer near the task inside the project**: At the current state of the app, it is possible to create multiple *active* timers for the same task. Is this expected behaviour? If that is the case, then how do we decide which timer to show inside the task card in the project page? @turabiapex 

[Figma link](https://www.figma.com/file/YXWLckXTIrvTJ7tdFJwwZh/Odoo-Timesheets--UX-Improvment-_-W.I.P?node-id=1114%3A1757&mode=dev)

**Comment by turabiapex** [comment]
@ajil-apx as we have a sort button on the figma at the bottom right corner of the page, I think we should stick to the default sorting behavior unless the user doesn't change that. plus, we will enable drag & drop very soon on this ticket here https://github.com/djangoflow/flutter-odoo-timesheets/issues/56

@ivan1px please feel free to comment on this argument. I would love to get your input.
