### ISSUE TITLE
Multiple timers support

### ISSUE THREAD

**Issue by ivan1px** [djangoflow/flutter-odoo-timesheets#5]
Figma design -> https://www.figma.com/file/A3qhLrXRCcLS0z4cEbq9Cz/odoo?node-id=0%3A1&t=DZeoKp8MNqlwhwvm-0

1. Add a button on the top right corner to select new Project->Task->Add description
2. After adding new timer to the page it should be listed on the screen according to the design
3. Change timer design
4. Stop button should be moved to the bottom of the screen. Clicking on it should submit all logged time.
5. Stop button should be visible even if there is a lot of timers on the screen
6. Starting another timer should automatically put previous one on pause
7. Below all timers should be displayed Total time
8. Change text from "Log work" to "Activity" 

![image](https://user-images.githubusercontent.com/116165418/220345617-3c800b2d-3579-4afc-8b2a-64bf9a7fc881.png)

**Comment by ayushin** [comment]
we need a way to fix a situation where i forgot to start or stop the timer.

**Comment by ivan1px** [comment]
Outdated
