### ISSUE TITLE
PM tasks Odoo

### ISSUE THREAD

**Issue by ivan1px** [djangoflow/flutter-odoo-timesheets#52]
- [ ] Explore the app flows
- [x] [Create tasks for missing micro iteractions](https://www.figma.com/file/YXWLckXTIrvTJ7tdFJwwZh/Odoo-Timesheets--UX-Improvment-_-W.I.P?type=design&node-id=2429-4319&mode=design&t=BoThIOVyNgmqCvMU-0)
- [ ] Make sure empty screens are updated
- [ ] Manage development
- [ ] QA of the app
- [ ] Research what we need to publish this app in the [odoo marketplace](https://apps.odoo.com/apps)
- [ ] Publish app for the app and play stores

**Comment by turabiapex** [comment]
micro interactions ticket created here https://github.com/djangoflow/flutter-odoo-timesheets/issues/56
