### ISSUE TITLE
Display a notification when timesheet was synced with odoo

### ISSUE THREAD

**Issue by ivan1px** [djangoflow/flutter-odoo-timesheets#6]
Display a notification when timesheet was synced with odoo

**Comment by shatanikmahanty** [comment]
@ivan1px by notification do you mean showing in app notification using a snackbar maybe or it is referring to android notifications in notification bar?

**Comment by ivan1px** [comment]
Snackbar will be okay. We should do the easy option.

**Comment by shatanikmahanty** [comment]
Available in latest deployment

**Comment by ivan1px** [comment]
Done
